name: Docker group name
on: [push]
jobs:
  docker_github_runner:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: groups
      - run: groups docker
      - run: id
  docker_buildjet_runner:
    runs-on: buildjet-2vcpu-ubuntu-2004
    steps:
      - run: whoami
      - run: groups
      - run: groups docker
      - run: id

